-- 학과, 학생, 과목, 교수, 과목-교수, 성적
-- 국어국문학과에 재학중인 학생
-- ABSENCE_YN : 휴학여부
SELECT	*
FROM	TB_STUDENT
-- INNER JOIN : 조건이 일치하는 행만 조회 - 누락되는 행이 발생
JOIN	TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE	DEPARTMENT_NAME = '국어국문학과' 
AND		ABSENCE_YN = 'N'; -- 휴학여부 컬럼을 이용해서 재학생만 조회

-- 여학생만 조회
SELECT	IF (SUBSTRING(STUDENT_SSN, 8, 1) IN (1, 3), '남', '여')
FROM	TB_STUDENT;
SELECT	*
FROM	TB_STUDENT
JOIN	TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE	SUBSTRING(STUDENT_SSN, 8, 1) IN (2, 4)
AND		DEPARTMENT_NAME = '국어국문학과'
AND		ABSENCE_YN = 'N';

-- 입학정원이 20명 이상 30명 이하인 학과의 이름과 계열을 출력
SELECT	DEPARTMENT_NAME, CATEGORY
FROM	TB_DEPARTMENT
-- WHERE	CAPACITY >= 20
-- AND		CAPACITY <=30;
WHERE	CAPACITY BETWEEN 20 AND 30;

-- 총장을 제외하고 모든 교수들이 소속 학과를 가지고 있다. 총장의 이름은?
SELECT	PROFESSOR_NAME
FROM	TB_PROFESSOR
WHERE	DEPARTMENT_NO IS NULL;

-- 전산상의 착오로 학과가 지정되어 있지 않은 학생이 있는지 확인해보자 
SELECT	*
FROM	TB_STUDENT
WHERE	DEPARTMENT_NO IS NULL;

-- 수강신청을 하려고 한다. 선수과목 여부를 확인해야 하는데, 선수과목이 존재하는 과목들은 어떤 과목인지 과목 번호를 조회
SELECT	DEPARTMENT_NO
FROM	TB_CLASS
WHERE	PREATTENDING_CLASS_NO IS NOT NULL;

-- 춘 대학에는 어떤 계열(CATEGORY)들이 있는지 조회
SELECT	DISTINCT CATEGORY
FROM	TB_DEPARTMENT;

-- 02학번 전주 거주자들의 모임 (휴학한 사람들은 제외한 재학중인 학생들의 학번, 이름, 주민번호를 출력) 
SELECT	STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM	TB_STUDENT
WHERE	STUDENT_NO LIKE 'A02%'
AND		STUDENT_ADDRESS LIKE '%전주%'
AND		ABSENCE_YN = 'N';

-- 영어영문학과(학과코드 002) 학생들의 학번과 이름, 입학 년도를 입학 년도가 빠른 순으로 표시하는 SQL문장을 작성하시오.
-- (단, 헤더는 "학번", "이름", "입학년도" 가 표시되도록 한다.) 
SELECT		STUDENT_NO 학번, STUDENT_NAME 이름, DATE_FORMAT(ENTRANCE_DATE, '%Y') 입학년도, EXTRACT(YEAR FROM ENTRANCE_DATE) 입학년도
FROM		TB_STUDENT
JOIN		TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE		DEPARTMENT_NAME = '영어영문학과'
ORDER BY	입학년도;

-- 2027-12-25 날짜로 변환
-- 앞에 있는 문자열의 형식과 뒤에 있는 형식이 일치해야 한다
SELECT	STR_TO_DATE('2027-12-25', '%Y-%m-%d') 날짜변환 ;

-- 교수 이름이 두글자인 사람
SELECT	*
FROM	TB_PROFESSOR
-- WHERE	CHAR_LENGTH(PROFESSOR_NAME) = 2
WHERE	PROFESSOR_NAME LIKE '__';
-- 교수 이름이 세글자가 아닌 사람
SELECT	*
FROM	TB_PROFESSOR
-- WHERE	CHAR_LENGTH(PROFESSOR_NAME) != 3
WHERE	PROFESSOR_NAME NOT LIKE '___';

-- 2000년도 이전 입학자들을 출력
SELECT	*
FROM	TB_STUDENT
-- WHERE	ENTRANCE_DATE NOT LIKE '20%'
WHERE	EXTRACT(YEAR FROM ENTRANCE_DATE) < 2000;

-- 학번이 A121056인 학생의 학점 중 평점을 구하는 SQL문
SELECT	TRUNCATE(AVG(POINT),2)
FROM	TB_GRADE
WHERE	STUDENT_NO = 'A121056';

-- 지도교수를 배정받지 못한 학생 수
SELECT	COUNT(STUDENT_NO)
FROM	TB_STUDENT
WHERE	COACH_PROFESSOR_NO IS NULL;

-- 동명이인의 이름과 수
SELECT	STUDENT_NAME 이름, COUNT(STUDENT_NAME) 수
FROM	TB_STUDENT
GROUP BY STUDENT_NAME
HAVING	수 > 1;

-- '인문사회' 계열에 속한 과목이름과 교수 이름
SELECT	CLASS_NAME, PROFESSOR_NAME
FROM	TB_CLASS
JOIN	TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN	TB_PROFESSOR USING (DEPARTMENT_NO)
WHERE	CATEGORY = '인문사회';

-- TB_CLASS_PROFESSOR (과목-교수)
SELECT	CLASS_NAME, PROFESSOR_NAME, D.DEPARTMENT_NAME
FROM	TB_CLASS C
JOIN	TB_CLASS_PROFESSOR USING (CLASS_NO)
JOIN	TB_PROFESSOR USING (PROFESSOR_NO)
JOIN	TB_DEPARTMENT D ON C.DEPARTMENT_NO = D.DEPARTMENT_NO
WHERE	D.CATEGORY = '인문사회';
