SET SESSION cte_max_recursion_depth = 5000;

DROP TABLE IF EXISTS BIG_EMP;

CREATE TABLE BIG_EMP AS
-- 가상 테이블
WITH RECURSIVE SEQ AS (		-- RECRUSIVE : 쿼리를 반복
    SELECT 1 AS N			-- N을 지정
    UNION ALL				-- 조건 더해주기
    SELECT N + 1 FROM SEQ WHERE N < 3000
)
SELECT ROW_NUMBER() OVER (ORDER BY S.N, E.EMP_ID) AS ID,
       E.EMP_NAME, E.DEPT_ID, E.JOB_CODE, E.SALARY, E.HIRE_DATE
FROM SEQ S
-- S의 행의 갯수 3000개 * E의 행의 갯수만큼 데이터를 출력
CROSS JOIN EMP E;

SELECT * FROM BIG_EMP;

-- 옵티마이저 실행계획
EXPLAIN SELECT * FROM BIG_EMP WHERE EMP_NAME = '곽상혁';

-- 인덱스의 이름
CREATE INDEX IDX_BIGEMP_NAME ON BIG_EMP(EMP_NAME);
EXPLAIN SELECT * FROM BIG_EMP WHERE EMP_NAME = '곽상혁';

SELECT * FROM BIG_EMP WHERE EMP_NAME = '곽상혁';
DROP INDEX IDX_BIGEMP_NAME ON BIG_EMP; -- 인덱스 제거

-- 클러스터 인덱스 생성 : 물리적으로 데이터를 정렬하여 보관
ALTER TABLE BIG_EMP ADD PRIMARY KEY (ID);
INSERT INTO BIG_EMP (ID, EMP_NAME) VALUES (0, '이미자');

DESC BIG_EMP;

SELECT COUNT(*) FROM BIG_EMP;                              -- 63000
SELECT COUNT(*) FROM BIG_EMP WHERE EMP_NAME = '곽상혁';    -- 3000