-- 환경변수 설정 : 함수 제약 없애기
SET GLOBAL LOG_BIN_TRUST_FUNCTION_CREATORS = 1;

DELIMITER $$

-- 연봉을 구하는 함수
CREATE FUNCTION FN_GET_ANNUAL_SALARY (P_SALARY INT, P_BONUS DECIMAL(4,2))
RETURNS INT
-- 동일한 입력값에 대해 항상 동일한 결과를 반환하는 함수
DETERMINISTIC
BEGIN 
	RETURN (P_SALARY + P_SALARY*IFNULL(P_BONUS,0)) * 12;
END $$

DELIMITER ;

SELECT FN_GET_ANNUAL_SALARY (2000000, 0.3);

SELECT EMP_NAME, SALARY, BONUS, FN_GET_ANNUAL_SALARY (SALARY, BONUS) 연봉
FROM EMP;

-- 나이를 반환하는 함수
DELIMITER $$
CREATE FUNCTION GET_AGE (P_EMP_NO CHAR(14))
RETURNS INT -- 선언할 때에는 S 붙은 RETURN'S'
-- NOW()함수를 사용하면 함수의 실행결과가 항상 같지 않다
-- READS SQL DATA
BEGIN
	DECLARE V_AGE INT;
    SET V_AGE = TIMESTAMPDIFF(YEAR, STR_TO_DATE( CASE WHEN SUBSTRING(P_EMP_NO, 8, 1) IN ('1', '2') THEN CONCAT('19', SUBSTRING(P_EMP_NO, 1, 6))
				WHEN SUBSTRING(P_EMP_NO, 8, 1) IN ('3', '4') THEN CONCAT('20', SUBSTRING(P_EMP_NO, 1, 6))
				END, '%Y%m%d'), NOW());
    RETURN V_AGE;
END $$
DELIMITER ;

DROP FUNCTION GET_AGE; -- 펑션 삭제하기

SELECT GET_AGE(EMP_NO)
FROM EMP;



-- ---------------------------
-- 프로시저 (Stored Procedure)
-- 여러개의 DML문장을 처리
-- ---------------------------
-- 부서 코드와 인상률을 파라메터로 전달받아 부서의 사원 급여를 인상하는 PROCEDURE
DELIMITER $$
-- 변수사용 : IN/ 되돌려주는값 : OUT
CREATE PROCEDURE RAISE_SALARY(IN P_DEPT_ID CHAR(2), IN P_RATE DECIMAL(3,2), OUT P_AVG_SALARY INT)
BEGIN
	UPDATE EMP
    SET SALARY = SALARY * (1 + P_RATE)
    WHERE DEPT_ID = P_DEPT_ID;
    
    -- SELECT 문의 조회결과를 변수에 담을 수 있다.
    -- 단일 행만 가능
    SELECT AVG(SALARY) INTO P_AVG_SALARY
    FROM EMP
    WHERE DEPT_ID = P_DEPT_ID;
    
    COMMIT;
END $$
DELIMITER ;

DROP PROCEDURE RAISE_SALARY;

-- 수정, 삭제 시 인덱스가 사용된 컬럼을 사용하지 않으면 오류를 발생시킴
SET SESSION SQL_SAFE_UPDATES = 0;

-- 사용법
-- OUT파라메터는 값을 반환
-- 사용자변수를 넣어주면 실행 결과를 변수에 담아줌
CALL RAISE_SALARY('D1', 0.1, @AVG_SAL);
-- 변수에 담긴 값 확인
SELECT @AVG_SAL;

SELECT * FROM EMP WHERE DEPT_ID = 'D1';

-- TEMPORARY : 현재 세션에서만 사용하고 사라지는 임시 테이블
CREATE TEMPORARY TABLE TMP_GUGU (DAN INT, I INT, RESULT INT);
DELIMITER $$
CREATE PROCEDURE GUGUDAN()
BEGIN
	DECLARE DAN INT DEFAULT 2;
    
    DAN_LOOP : LOOP
		
		IF DAN > 9 THEN LEAVE DAN_LOOP;
        END IF;
        
        INSERT INTO TMP_GUGU VALUES(DAN, 0, 0);
		SET DAN = DAN + 1; -- 변수 값의 업데이트
        
	END LOOP;
END $$
DELIMITER ;

CALL GUGUDAN();
SELECT * FROM TMP_GUGU;

-- 여러 행에 대한 처리 : CURSOR
DROP TABLE IF EXISTS EMP_COPY;
CREATE TABLE EMP_COPY AS SELECT * FROM EMP;

DROP TABLE IF EXISTS SALARY_LOG;
CREATE TABLE SALARY_LOG (
    LOG_ID     INT AUTO_INCREMENT PRIMARY KEY,
    EMP_ID     VARCHAR(3),
    OLD_SALARY INT,
    NEW_SALARY INT,
    CHANGED_AT DATETIME DEFAULT NOW()
); 
DELIMITER $$
CREATE PROCEDURE FLAG_LOW_SALARY()
BEGIN
	-- 변수선언
	DECLARE V_DONE INT DEFAULT 0; -- 반복문의 탈출 조건 설정준비
    DECLARE V_EMP_ID VARCHAR(3);
    DECLARE V_SALARY INT;
    
    -- 커서 선언
    DECLARE CUR CURSOR FOR
		SELECT EMP_ID, SALARY FROM EMP;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET V_DONE = 1; -- 반복문 탈출 조건2
    
    -- 쿼리의 실행, FETCH 준비
    OPEN CUR;
    READ_LOOP : LOOP
		FETCH CUR INTO V_EMP_ID, V_SALARY;
        IF V_DONE = 1 THEN
			LEAVE READ_LOOP;
        END IF;
        
	IF V_SALARY < 2000000 THEN
	-- 급여 이력 테이블
		INSERT INTO SALARY_LOG (V_EMP_ID, V_SALARY, V_SALARY);
	END IF;
    
    END LOOP;
    CLOSE CUR;
    
END $$
DELIMITER ;
