-- DDL
-- DBMS에서 제공해주는 여러가지 객체를 CREATE생성, ALTER수정, DROP삭제
-- CREATE TABLE 테이블명 (
-- 	컬럼이름 타입 [제약조건],
-- 	컬럼이름 타입 [제약조건]
-- );
-- AUTO_INCREMENT : 식별자. 값을 입력하지 않아도 1부터 시작해서 1씩 증가하는 일련번호 입력
-- PrimaryKey : PK. 식별자. 중복이 될 수 없고 NULL을 입력할 수 없음 - 하나의 행을 유일무이하게 구분
-- NOT NULL : 필수입력
CREATE TABLE MEMBER (
    MEMBER_ID INT          AUTO_INCREMENT PRIMARY KEY,
    NAME      VARCHAR(20)  NOT NULL,
    PHONE     VARCHAR(20)  NOT NULL,
    ADDRESS   VARCHAR(100)
);
CREATE TABLE BOOK (
    BOOK_ID INT           AUTO_INCREMENT PRIMARY KEY,
    TITLE   VARCHAR(100)  NOT NULL,
    AUTHOR  VARCHAR(50)
);
CREATE TABLE RENTAL_STATUS_CODE (
    STATUS_CODE VARCHAR(10) PRIMARY KEY,
    STATUS_NAME VARCHAR(20) NOT NULL
);

-- 외래키 제약조건을 적용하는 경우, 참조될 테이블이 미리 생성되어있어야 한다
CREATE TABLE RENTAL (
    RENTAL_ID    INT          AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID    INT          NOT NULL,
    BOOK_ID      INT          NOT NULL,
    RENTAL_DATE  DATE         NOT NULL,
    RETURN_DATE  DATE,
    STATUS_CODE  VARCHAR(10)  NOT NULL,
    -- CONSTRAINT 제약조건이름 FOREIGN KEY (컬럼이름) REFERENCES 참조테이블명 (컬럼명)
    -- 데이터의 무결성 유지
    -- 사원테이블의 사원ID 참조하면 등록되지않은 사원ID입력시 오류가 발생
    CONSTRAINT FK_RENTAL_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT FK_RENTAL_BOOK   FOREIGN KEY (BOOK_ID)   REFERENCES BOOK (BOOK_ID),
    CONSTRAINT FK_RENTAL_STATUS FOREIGN KEY (STATUS_CODE) REFERENCES RENTAL_STATUS_CODE (STATUS_CODE)
);

-- 테이블 삭제
DROP	TABLE RENTAL;
DROP	TABLE RENTAL_STATUS_CODE;
DROP	TABLE MEMBER;
DROP	TABLE BOOK;

-- EMP_COPY테이블만들기
-- EMP_ID   	VARCHAR(3)   PK, 자동증가
-- EMP_NAME 	VARCHAR(20)
-- EMP_NO 		CHAR(14)
-- JOB_CODE		CHAR(2)		FK(JOB테이블의 JOB_CODEF를 참조하고 이름은 FK_EMPCOPY_JOB) 
CREATE TABLE EMP_COPY (
	EMP_ID		INT			AUTO_INCREMENT PRIMARY KEY,
    EMP_NAME	VARCHAR(20)	,
    EMP_NO		CHAR(14)	,
    JOB_CODE	CHAR(2)		,
    -- 참조키 : 다른 테이블의 기본키를 참조
    -- JOB테이블의 기본키를 먼저 실행
    CONSTRAINT FK_EMPCOPY_JOB FOREIGN KEY (JOB_CODE) REFERENCES JOB (JOB_CODE)
);
    
-- 테이블의 구조를 변경 - 기본키 지정
ALTER TABLE JOB ADD PRIMARY KEY (JOB_CODE);
    
-- 여러 문장을 스크립트로 작성 후 실행할 때 오류가 발생하면 멈춤
-- 경고메세지만 출력 후 다음 진행: 
DROP TABLE IF EXISTS EMP_COPY;
    
-- 테이블을 복사해서 만들기
-- SELECT문의 결과집합을 테이블로 생성 -> 결과집합의 데이터가 있다면 데이터까지 입력해줌
-- CREATE TABLE 테이블이름 AS SELECT문;
-- 제약조건은 복사되지 않는다!
CREATE TABLE EMP_BK AS SELECT * FROM EMP;

-- 테이블의 구조만 복사
CREATE TABLE EMP_COPY AS SELECT EMP_ID, EMP_NAME FROM EMP WHERE 1=0;

-- VIEW를 이용해서 테이블 만들기
CREATE TABLE VIEW_BK AS SELECT * FROM EMP_MASTER;

CREATE TABLE EMP_COPY (
    EMP_ID     VARCHAR(3) PRIMARY KEY,
    EMP_NAME   VARCHAR(20) NOT NULL,
    EMAIL      VARCHAR(25) UNIQUE,
    DEPT_ID    CHAR(2),
    JOB_CODE   CHAR(2),
    SALARY     INT DEFAULT 0,
    MANAGER_ID VARCHAR(3),
    HIRE_DATE  DATE NOT NULL,
    ENT_YN     CHAR(1) DEFAULT 'N' CHECK (ENT_YN IN ('Y', 'N')),
    CONSTRAINT FK_EMPCOPY_DEPT    FOREIGN KEY (DEPT_ID)    REFERENCES DEPT(DEPT_ID),
    CONSTRAINT FK_EMPCOPY_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES EMP_COPY(EMP_ID)
);

-- 테이블의 구조 확인
DESC EMP_COPY;

-- DML문 : 데이터의 삽입, 삭제, 수정
-- 데이터 삽입
-- 모든 컬럼에 데이터를 입력 : 컬럼지정 없이 데이터만 순서대로 입력
-- INSERT INTO 테이블이름 VALUES (컬럼에 입력될 값, ...);
-- 일부 컬럼에 데이터를 입력
-- INSERT INTO 테이블이름 (컬럼지정, ..) VALUES (컬럼에 입력될 값, ...);
-- SYSDATE() : 현재 날짜와 시간을 반환하는 기본 내장함수
-- CURDATE() : 현재의 날짜만 반환
INSERT INTO EMP_COPY (EMP_ID, EMP_NAME, HIRE_DATE) VALUES ('001', '오미자', SYSDATE());
-- INSERT INTO EMP_COPY (EMP_ID, EMP_NAME, HIRE_DATE, ENT_YN) VALUES ('001', '오미자', SYSDATE(), 'A'); 
INSERT INTO EMP_COPY (EMP_ID, EMP_NAME, HIRE_DATE, DEPT_ID) VALUES ('002', '이미자', CURDATE(), 'D1');
-- 날짜입력 시 문자형식으로 입력해도 자동형변환에 의해 날짜타입으로 변환되어 입력됨
INSERT INTO EMP_COPY (EMP_ID, EMP_NAME, HIRE_DATE, DEPT_ID) VALUES ('003', '정미자', '2026-08-01', 'D1');

SELECT * FROM EMP_COPY;

-- DDL은 실행과 동시에 커밋 -> 취소가 불가능!
-- 테이블 이름 변경
RENAME TABLE EMP_COPY TO EMPLOYEE;

-- EMP_COPY 생성, 기본키 외래키 추가
CREATE TABLE EMP_COPY AS SELECT * FROM EMP;
ALTER TABLE EMP_COPY ADD CONSTRAINT PK_EMP_COPY PRIMARY KEY (EMP_ID);
-- DEPT테이블의 구조와 데이터를 모두 복사 -> DEPT_COPY
-- DEPT_ID에 기본키 제약조건 추가
CREATE TABLE DEPT_COPY AS SELECT * FROM DEPT;
ALTER TABLE DEPT_COPY ADD CONSTRAINT PK_DEPT_COPY PRIMARY KEY (DEPT_ID);

-- 제약조건 추가
-- 제약조건의 이름은 중복될 수 없다
ALTER TABLE EMP_COPY ADD CONSTRAINT FK_EMPCOPY_DEPT_1 FOREIGN KEY (DEPT_ID) REFERENCES DEPT_COPY(DEPT_ID);

-- 4.2 컬럼 추가 — ADD COLUMN (기존 행은 전부 NULL로 채워짐)
ALTER TABLE EMP_COPY ADD COLUMN REMARK VARCHAR(50) NOT NULL;
DESC EMP_COPY; -- 정보 확인

-- 4.3 컬럼 변경 — MODIFY COLUMN (이름은 그대로, 정의만 변경)
ALTER TABLE EMP_COPY MODIFY COLUMN REMARK VARCHAR(100) DEFAULT 'N' NOT NULL;

-- 4.4 컬럼 삭제 — DROP COLUMN
ALTER TABLE EMP_COPY DROP COLUMN REMARK;

-- 4.5 이름 변경 — RENAME COLUMN / RENAME TABLE
ALTER TABLE EMP_COPY RENAME COLUMN EMP_NO TO RESIDENT_NO;    -- 컬럼이름 변경
ALTER TABLE EMP_COPY RENAME TO STAFF;   -- 테이블 이름 변경
ALTER TABLE STAFF RENAME TO EMP_COPY;   -- 원래 이름으로 되돌림 

-- 테이블 삭제 : 구조와 데이터를 모두 삭제
DROP TABLE EMP_COPY;

SELECT * FROM DEPT_COPY;
-- 데이터만 삭제
TRUNCATE TABLE DEPT_COPY;
